sampleproj/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^tcsproject/', include('tcsproject.urls')),
]

tcsproject/urls.py
from django.conf.urls import url

from . import views

app_name = 'tcsproject'
urlpatterns = [
    url(r'^home/$', views.home, name="home"),
    url(r'^categories/(?P<id>[a-zA-Z ]+)/$', views.categories, name='categories'),
    url(r'^new/$', views.addnewthesis, name='addnewthesis'),
    # url(r'^thesis/(?P<id>[0-9]+)/$', views.viewthesis, name='viewthesis'),
    url(r'^thesis/(?P<id>[0-9]+)/delete/$', views.deletethesis, name='deletethesis'),
     url(r'^thesis/(?P<thesis>.+)/(?P<session_id>[0-9]+)/like/$', views.likethesis, name='like'),
    url(r'^send/$', views.sendemail, name='sendemail'),
    url(r'^home/search=(?P<thesis>.*)/', views.searchthesis, name='search'),
    url(r'^thesis/(?P<id>[0-9]+)/$', views.thesis_view, name='thesisview'),
    url(r'^thesis/all/$', views.viewall, name='viewall'),
    url(r'^thesis/all/published/$', views.viewallbypublished, name='viewallbypublished'),
    url(r'^thesis/all/authors/$', views.viewallbyauthor, name='viewallbyauthor'),
    url(r'^thesis/all/added/$', views.viewallbyadded, name='viewallbyadded'),
    #url(r'^categories/[a-zA-z]+/$', views.category, name='category'),
]

tcsproject/models.py
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils import timezone

class Thesis(models.Model):
    title = models.CharField(max_length=300,blank=False, unique=True)
    authors = models.CharField(max_length=300,blank=False)
    emails = models.EmailField(blank=False,default='')
    desc = models.TextField(blank=False)
    abstract = models.TextField(blank=False)
    no_of_pages = models.IntegerField(blank=False)
    date_published = models.DateField(auto_now=False, auto_now_add=False)
    date_added = models.DateField(auto_now=False, auto_now_add=True)
    DEPTS = [
     ('Accountancy','Accountancy'),
     ('Banking and Finance','Banking and Finance'),
     ('Management','Management'),
     ('Marketing','Marketing'),
     ('Customs Administration','Customs Administration'), 
     ('Hospitality Management','Hospitality Management'),
     ('Filipino','Filipino'),
     ('English and Foreign Language','English and Foreign Language'), 
     ('Physical Education','Physical Education'), 
     ('Social Science','Social Science'),
     ('Chemical Engineering','Chemical Engineering'), 
     ('Civil Engineering','Civil Engineering'), 
     ('Computer Engineering','Computer Engineering'), 
     ('Electrical Engineering','Electrical Engineering'),
     ('Electronics Engineering','Electronics Engineering'), 
     ('Industrial Engineering','Industrial Engineering'),
     ('Mechanical Engineering','Mechanical Engineering'), 
     ('Mining, Geology, and Ceramics Engineering','Mining, Geology, and Ceramics Engineering'),
     ('Biology','Biology'), 
     ('Chemistry','Chemistry'), 
     ('Computer Science','Computer Science'), 
     ('Mathematics','Mathematics'), 
     ('Psychology','Psychology'), 
     ('Information Technology and Management','Information Technology and Management')
     ]
    dept = models.CharField(max_length=300, choices = sorted(DEPTS), blank=False)
    CATEGORIES = [
    ('Books','Books'), 
    ('Business','Business'), 
    ('Catalogs','Catalogs'), 
    ('Education','Education'),
    ('Entertainment','Entertainment'), 
    ('Finance','Finance'), 
    ('Food and Drink','Food and Drink'), 
    ('Games','Games'), 
    ('Health and Fitness','Health and Fitness'),
    ('Lifestyle','Lifestyle'), 
    ('Magazines and Newspaper','Magazines and Newspaper'), 
    ('Medical','Medical'), 
    ('Music','Music'), 
    ('Navigation','Navigation'), 
    ('News','News'), 
    ('Photo and Video','Photo and Video'), 
    ('Productivity','Productivity'), 
    ('Reference','Reference'), 
    ('Shopping','Shopping'),
    ('Social Networking','Social Networking' ), 
    ('Sports','Sports'), 
    ('Travel','Travel'), 
    ('Utilities','Utilities'), 
    ('Weather','Weather')
    ]
    category = models.CharField(max_length=300, choices = sorted(CATEGORIES), blank=False)
    likes = models.IntegerField(default=0)

    def __str__(self):
        return self.title + " by " + self.authors
        
    class Meta:
        verbose_name='Thesis'

class Like(models.Model):
    thesis = models.ForeignKey(Thesis)
    session = models.CharField(max_length=500)

    def __str__(self):
        return str(self.thesis)

tcsproject/forms.py
from django import forms
from models import Thesis
from django.forms import ModelForm

class AddThesisForm(forms.ModelForm):
	class Meta:
		model = Thesis
		fields = ['title',
				  'authors',
				  'emails',
				  'desc',
				  'abstract',
				  'no_of_pages',
				  'date_published',
				  'dept',
				  'category']

class ContactForm(forms.Form):
	name = forms.CharField(required=True)
	message = forms.CharField(max_length=500, widget=forms.Textarea, required=True)

class LikeForm(forms.Form):
	thesis = forms.CharField(max_length=500)
	like = forms.IntegerField()
	session_id = forms.CharField(max_length=500)

class SearchForm(forms.Form):
	thesis_title = forms.CharField(max_length=500)

tcsproject/views.py
from django.http import HttpResponse, HttpResponseRedirect,Http404
from django.shortcuts import get_object_or_404, render, redirect
from .models import Thesis, Like
from .forms import AddThesisForm, ContactForm, LikeForm, SearchForm
from django.contrib.auth.models import User
from django.template.loader import get_template
from django.core.mail import EmailMessage
from django.contrib import messages
from django.core.mail import send_mail
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import random
import datetime, time
import collections
from django.template import Context

def home(request):
    template_name = 'tcsproject/home.html'
    user = request.user
    ts = time.time()
    session_id = datetime.datetime.fromtimestamp(ts).strftime('%Y%m%d')
    request.session['session_id'] = session_id
    likeform = LikeForm()
    likes = collections.Counter(Like.objects.all())
    print likes
    thesis = Thesis.objects.all()
    
    thesis_likes = {}
    for i in thesis:
    	thesis_likes[i.title] = len(Like.objects.filter(thesis = i))

    if request.method == 'POST':
    	contactform = ContactForm(request.POST)
    	if contactform.is_valid():
    		contact = contactform.save(commit=False)
    		contact.save()
    else:
    	contactform = ContactForm()
    print thesis_likes


    allthesis = Thesis.objects.all()
    paginator = Paginator(allthesis, 4)

    page = request.GET.get('page')
    try:
        thesis_by_8 = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        thesis_by_8 = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        thesis_by_8 = paginator.page(paginator.num_pages)
    
    context = {'recently_added': Thesis.objects.order_by('-date_added')[:4]
    ,
               'featured' : Thesis.objects.order_by('-likes')[:4],
               'contactform':contactform,
               'session':session_id,
               'likeform':likeform,
               'likes': thesis_likes
              }
    return render(request, template_name, context)


def viewall(request):
    template_name = 'tcsproject/viewall.html'
    allthesis = Thesis.objects.all()
    paginator = Paginator(allthesis, 8)

    page = request.GET.get('page')

    try:
        thesis_by_8 = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        thesis_by_8 = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        thesis_by_8 = paginator.page(paginator.num_pages)

    thesis = Thesis.objects.all()
    thesis_likes = {}
    for i in thesis:
        thesis_likes[i.title] = len(Like.objects.filter(thesis = i))

    context = {'viewall': thesis_by_8,
    'likes': thesis_likes
            }
    return render(request, template_name, context)

def viewallbyauthor(request):
    template_name = 'tcsproject/viewall.html'
    allthesis = Thesis.objects.all().order_by('-authors')
    paginator = Paginator(allthesis, 8)

    page = request.GET.get('page')

    try:
        thesis_by_8 = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        thesis_by_8 = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        thesis_by_8 = paginator.page(paginator.num_pages)

    thesis = Thesis.objects.all()
    thesis_likes = {}
    for i in thesis:
        thesis_likes[i.title] = len(Like.objects.filter(thesis = i))

    context = {'viewall': thesis_by_8,
    'likes': thesis_likes
            }
    return render(request, template_name, context)

def viewallbypublished(request):
    template_name = 'tcsproject/viewall.html'
    allthesis = Thesis.objects.all().order_by('-date_published')
    paginator = Paginator(allthesis, 8)

    page = request.GET.get('page')

    try:
        thesis_by_8 = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        thesis_by_8 = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        thesis_by_8 = paginator.page(paginator.num_pages)

    thesis = Thesis.objects.all()
    thesis_likes = {}
    for i in thesis:
        thesis_likes[i.title] = len(Like.objects.filter(thesis = i))

    context = {'viewall': thesis_by_8,
    'likes': thesis_likes
            }
    return render(request, template_name, context)

def viewallbyadded(request):
    template_name = 'tcsproject/viewall.html'
    allthesis = Thesis.objects.all().order_by('-date_added')
    paginator = Paginator(allthesis, 8)

    page = request.GET.get('page')

    try:
        thesis_by_8 = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        thesis_by_8 = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        thesis_by_8 = paginator.page(paginator.num_pages)

    thesis = Thesis.objects.all()
    thesis_likes = {}
    for i in thesis:
        thesis_likes[i.title] = len(Like.objects.filter(thesis = i))

    context = {'viewall': thesis_by_8,
    'likes': thesis_likes
            }
    return render(request, template_name, context)


def categories(request,id=id):
    template_name = 'tcsproject/categories.html'
    thesis_likes = {}
    thesis_by_8 = []
    if not len(Thesis.objects.filter(category=id)) == 0:
        thesis_by_8 = Thesis.objects.filter(category=id)
        thesis = Thesis.objects.all()
        for i in thesis:
            thesis_likes[i.title] = len(Like.objects.filter(thesis = i))
        paginator = Paginator(thesis_by_8, 8)

        page = request.GET.get('page')

        try:
            thesis_by_8 = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            thesis_by_8 = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            thesis_by_8 = paginator.page(paginator.num_pages)

    else:
        thesis_by_8 = 'None'

    context = {'categories' : thesis_by_8,
			   'category' : id,
               'likes':thesis_likes
			  }
    return render(request, template_name, context)

def viewthesis(request, id=id):
	template_name = 'tcsproject/thesis.html'
	context = {'topic' : Thesis.objects.get(pk=id)}
	return render(request, template_name, context)

def addnewthesis(request):
	template_name = 'tcsproject/new.html'
	if request.user.is_authenticated:
		if request.method == 'POST':
			form = AddThesisForm(request.POST)
			if form.is_valid():
				thesis = form.save(commit=False)
				thesis.save()
				return HttpResponseRedirect('/tcsproject/home/')
		else:
			form = AddThesisForm()
	else:
		raise Http404("Page does not exist")
	context = {'newthesis':form}
	return render(request, template_name, context)

def deletethesis(request,id=id):
    if request.user.is_authenticated:
	   Thesis.objects.filter(id=id).delete()
	   return HttpResponseRedirect('/tcsproject/home/')
    else:
        raise Http404("Page does not exist")

def sendemail(request):
    if request.method == 'POST':
        contactform = ContactForm(request.POST)
        if contactform.is_valid():
            email = contactform.data['email']
            msg = contactform.data['message']
            send_mail('A comment to your thesis', msg, '<amiel.garra@outlook.com>', [email])
            return HttpResponse('Success')
    else:
        contactform = ContactForm()
    return HttpResponse('HEY')

def likethesis(request, thesis, session_id):
    t = Thesis()
    t = Thesis.objects.get(title=thesis)
    if len(Like.objects.filter(thesis=t, session=session_id)) == 0:
    	like = Like()
    	like.thesis = t
    	like.session = session_id
    	like.save()
    	messages.add_message(request, messages.SUCCESS, 'You liked ' + t.title +".")
        return redirect('/tcsproject/thesis/'+str(t.id))
    else:
        messages.add_message(request, messages.SUCCESS, 'You already liked ' + t.title +".")
    	return redirect('/tcsproject/thesis/'+str(t.id))

def searchthesis(request, thesis):
    template_name = 'tcsproject/results.html'
    ts = time.time()
    session_id = datetime.datetime.fromtimestamp(ts).strftime('%Y%m%d')
    request.session['session_id'] = session_id
    if thesis == "":
        return HttpResponseRedirect('/tcsproject/home/')
    results = Thesis.objects.filter(title__icontains = thesis)
    print results   
    likeform = LikeForm()
    likes = collections.Counter(Like.objects.all())
    print likes
    thesis = Thesis.objects.all()
    thesis_likes = {}
    for i in thesis:
        thesis_likes[i.title] = len(Like.objects.filter(thesis = i))
    if request.method == 'POST':
        contactform = ContactForm(request.POST)
        if contactform.is_valid():
            contact = contactform.save(commit=False)
            contact.save()
    else:
        contactform = ContactForm()
    print thesis_likes

    paginator = Paginator(results, 8)

    page = request.GET.get('page')

    try:
        results = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        results = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        results = paginator.page(paginator.num_pages)

    thesis = Thesis.objects.all()

    context = {'results':results,
               'contactform':contactform,
               'session':session_id,
               'likeform':likeform,
               'likes':thesis_likes}

    return render(request, template_name, context)


def thesis_view(request, id=id):
    template_name='tcsproject/thesis.html'
    user = request.user
    ts = time.time()

tcsproject/templates/tcsproject/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Thesis Collection System</title>
    <style>
    #of {
    overflow: hidden;
    text-overflow: ellipsis;
    }
    </style>
    {% load widget_tweaks %}
    {% load static %}
    <!-- Bootstrap -->
    <link href="{% static 'tcsproject/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
	<!-- Custom styles for this template -->
	<link href="{% static 'tcsproject/navigation.css' %}" rel="stylesheet" type="text/css">

    <script src="{% static 'tcsproject/js/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'tcsproject/js/bootstrap.min.js' %}"></script>
    
<script type="text/javascript">
    $(window).ready(function(){
        $("#myMessage").modal('show');
    });

//     $('input[name="q"]').change(function(){
// alert($('#searchBtn').attr('href')+$('input[name="q"]').val());
// });

    $(function() {
    $('#searchBtn').click( function() {
        window.location = $(this).attr('href') + $('#q').val();
        return false;
    });
});
</script>

<style>

  #whiteh3 h4{
    color: #ecf0f1;
  }
</style>

  </head>

<body>

<nav class="navbar navbar-inverse navbar-static-top example-8">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar8">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand text-hide" href="#">Brand Text
        </a>
      </div>
      <div id="navbar8" class="navbar-collapse collapse">
      </ul>
        <ul class="nav navbar-nav navbar-right">
        <div class="col-bg-3 col-md-12">
        <form class="navbar-form" role="search" action="">
        <div class="input-group">
            <input type="text" class="form-control" placeholder="Search" name="q" id="q">
            

            <div class="input-group-btn">
                <button class="btn btn-default" type="submit" id="searchBtn" href="/tcsproject/home/search=">
            
                <i class="glyphicon glyphicon-search"></i></button>
            </div>
        </div>
        </form>
    </div>
    </ul>
        <ul class="nav navbar-nav navbar-right">
          <li class=""><a href="{% url 'tcsproject:home' %}">Home</a></li>
          <li class=""><a href="{% url 'tcsproject:viewall' %}">All Thesis</a></li>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="{% url 'tcsproject:categories' id='Books' %}">Books</a></li>
              <li><a href="{% url 'tcsproject:categories' id='Catalogs' %}">Catalogs</a></li>
              <li><a href="{% url 'tcsproject:categories' id='Education' %}">Education</a></li>
              <li><a href="{% url 'tcsproject:categories' id='Entertainment' %}">Entertainment</a></li>
              <li><a href="{% url 'tcsproject:categories' id='Finance' %}">Finance</a></li>
              <li><a href="{% url 'tcsproject:categories' id='Food and Drink' %}">Food and Drink</a></li>
              <li><a href="{% url 'tcsproject:categories' id='Games' %}">Games</a></li>
              <li><a href="{% url 'tcsproject:categories' id='Health and Fitness' %}">Health and Fitness</a></li>
              <li><a href="{% url 'tcsproject:categories' id='Lifestyle' %}">Lifestyle</a></li>
              <li><a href="{% url 'tcsproject:categories' id='Magazines and Newspaper' %}">Magazines and Newspaper</a></li>
              <li><a href="{% url 'tcsproject:categories' id='Medical' %}">Medical</a></li>
              <li><a href="{% url 'tcsproject:categories' id='Music' %}">Music</a></li>
              <li><a href="{% url 'tcsproject:categories' id='Navigation' %}">Navigation</a></li>
              <li><a href="{% url 'tcsproject:categories' id='News' %}">News</a></li>
              <li><a href="{% url 'tcsproject:categories' id='Photo and Video' %}">Photo and Video</a></li>
              <li><a href="{% url 'tcsproject:categories' id='Productivity' %}">Productivity</a></li>
              <li><a href="{% url 'tcsproject:categories' id='Reference' %}">Reference</a></li>
              <li><a href="{% url 'tcsproject:categories' id='Shopping' %}">Shopping</a></li>
              <li><a href="{% url 'tcsproject:categories' id='Social Networking' %}">Social Networking</a></li>
              <li><a href="{% url 'tcsproject:categories' id='Sports' %}">Sports</a></li>
              <li><a href="{% url 'tcsproject:categories' id='Travel' %}">Travel</a></li>
              <li><a href="{% url 'tcsproject:categories' id='Utilities' %}">Utilities</a></li>
              <li><a href="{% url 'tcsproject:categories' id='Weather' %}">Weather</a></li>
            </ul>
          </li>
          {% if request.user.is_authenticated %}
          <li class=""><a href="{% url 'tcsproject:addnewthesis' %}">New</a></li>
          {% endif %}
        
      </div>
      <!--/.nav-collapse -->
    </div>
    <!--/.container-fluid -->
  </nav>
{% block content %}

{% endblock %}
</body>

</html>

tcsproject/templates/tcsproject/detail.html
<html>
<title>Sample</title>
<head>

</head>
<body>
<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul>

<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'tcsproject:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>
</body>
</html>

tcsproject/templates/tcsproject/new.html
{% extends 'tcsproject/base.html' %}
{% block content %}

{% load widget_tweaks %}
<style>
#right input {
    float:right;
    clear:both;
}
</style>
<div class="container-fluid">
  <div class="col-lg col-lg-8 col-lg-offset-2">
    <div class="thumbnail" style="min-height: 200px; height: auto; width: auto;">
      <div class="caption">
      <h4>Add New Thesis</h4>
        <form action="{% url 'tcsproject:addnewthesis' %}" method="post">
        {% csrf_token %}
    
        <div class="form-group">
          <div class="col-lg-6">
            {{ newthesis.title.error}}
            {{ newthesis.title|add_class:'form-control'|attr:'placeholder:Title'}}<br>
            
          </div>
          <div class="col-lg-6">
            {{ newthesis.authors.error}}
            {{ newthesis.authors|add_class:'form-control'|attr:'placeholder:Authors (separated by comma)'}}<br>
          </div>
          <div class="col-lg-12">
            {{ newthesis.desc|add_class:'form-control'|attr:'placeholder:Description'|attr:'rows:3'}}<br>
          </div>
          <div class="col-lg-12">
            {{ newthesis.abstract|add_class:'form-control'|attr:'placeholder:Abstract'|attr:'rows:3'}}<br>
          </div>
          <div class="col-lg-4">
            {{ newthesis.date_published.error}}
            {{ newthesis.date_published|add_class:'form-control'|attr:'placeholder:Date published (yyyy-mm-dd)'}}<br>
          </div>
          <div class="col-lg-4">
            {{ newthesis.emails.error}}
            {{ newthesis.emails|add_class:'form-control'|attr:'placeholder:Email'}}<br>
          </div>
          <div class="col-lg-4">
            {{ newthesis.no_of_pages.error}}
            {{ newthesis.no_of_pages|add_class:'form-control'|attr:'placeholder:Number of pages'}}<br>
          </div>
          <div class="col-lg-6">
            {{ newthesis.dept|add_class:'form-control'}}<br>
          </div>
          <div class="col-lg-6">
            {{ newthesis.category|add_class:'form-control'}}<br>
          </div>
        </div>
        <div align="right">
          <input class="btn btn-primary" type="submit" value="Add Thesis"/>
        </div>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

tcsproject/templates/tcsproject/thesis.html
{% extends 'tcsproject/base.html' %}
{% block content %}
{% load widget_tweaks %}

<style>
  #whiteh3 h3,h4{
    color:#ecf0f1;
  }
  #grayh3 h3,h4,h2,h1,h5{
    color:#2c3e50;
  }

#white h1,h2,h3{
	color:#ecf0f1
}

#w74 { word-wrap: break-word; }

#inlineform form{
	display: inline-block;
   }
</style>

{% if messages %}
<div class="modal fade bd-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true" id="myMessage">
  <div class="modal-dialog modal-sm" role="document" id="grayh3">
      {% for message in messages %}
        <center><h2 class="modal-title" id="grayh3">{{message}}</h2></center>
      {% endfor %}
  </div>
</div>
{% endif %}

<div class="container">
<div class="row">
<div class="col-lg-12 col-md-3" id="grayh3">
    <div class="thumbnail" style="min-height: auto; height: auto; width: auto;">
    <div class="header" id="w74">
      <center><h3>{{topic.title}}</h3></center>
      <center><h4><small>{{topic.desc}}</small></h4></center>
      <center>by<h4><small><strong>{{topic.authors}}</strong></small></h4></center>
    </div>
      <div class="caption">
        <hr>
        <div>
        <center><h4>Abstract</h4></center>
        </div>
        <div id="w74">
        {{topic.abstract}}
        </div>
        <!-- </div> -->
        <br>
        <hr>
        <div>
        <i>Date published: </i>{{topic.date_published}}
        </div>
        <div>
        <i>Date added: </i>{{topic.date_added}}
        </div>
        <br>
        <br>
        <div><i>Likes: </i>
        {% for key, value in likes.iteritems %}
          {% if key == topic.title %}
            {{value}}
          {% endif %}
        {% endfor %}
        </div>
        <br>
        <div class="form-group" id="inlineform">
        {% if request.user.is_authenticated %}
		<form action="{% url 'tcsproject:deletethesis' id=topic.id %}">
		<input style="display:inline;" type="submit" name="delete" class="btn btn-danger" value="Delete"/>
		</form>
		{% endif %}
		<form action="{% url 'tcsproject:like' thesis=topic.title session_id=session %}" method="POST">
        {% csrf_token %}
        <button class="btn btn-primary" type="submit" value="Like"><span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span> Like</button>
      	</form>
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
  Contact the authors
</button>
		</div>

        </div>
      </div>
</div>
</div>
</div>

<div class="modal fade" id="myModal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">Contact authors</h4>
      </div>
      <form action="{% url 'tcsproject:thesisview' id=topic.id %}" method="post">
      {% csrf_token %}
      <div class="modal-body">
        {{contactform.name|add_class:'form-control'|attr:'placeholder:Name'}}<br>
        {{contactform.message|add_class:'form-control'|attr:'placeholder:Message'}}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <input class="btn btn-primary" type="submit" value="Send Message"/>
      </div>
      </form>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
{% endblock %}